### ISSUE TITLE
Error about "GFF_extract_features.py"

### ISSUE THREAD

**Issue by unavailable-2374** [andreaminio/AnnotationPipeline-EVM_based-DClab#3]
Commnd：“python3 tools/Scripts/GFF_extract_features.py -g mmpt_1.fa -a R1.stringtie.transdecoder.gff3 -p R1.stringtie.transdecoder.clean > R1.stringtie.transdecoder.clean.log”

Error：  File "/public/agis/zhouyongfeng_group/caoshuo/anno/tools/Scripts/GFF_extract_features.py", line 1189
    for g_key, g_value in sorted(genes.iteritems(), key=lambda (k, v): itemgetter(1, 2)(v)):
                                ^
SyntaxError: expected ':'

Python 3.10.3

thanks!

**Comment by andreaminio** [comment]
Hi,

The issue is with the python version. The script is made in python 2, not python 3. 

Try running it like this requiring explicitly python 2:
`python2 tools/Scripts/GFF_extract_features.py -g mmpt_1.fa -a R1.stringtie.transdecoder.gff3 -p R1.stringtie.transdecoder.clean > R1.stringtie.transdecoder.clean.log`

**Comment by unavailable-2374** [comment]
thanks！
